# Testing arrays

In [1]:
import numpy as np

In [2]:
x_list = []
x1 = np.array([[1, 2]])
print(x1)
x_list.append(x1)
x2 = np.array([[3, 4]])
print(x2)
x_list.append(x2)
x_comb = np.concatenate(x_list, axis=0)
print(x_comb)

[[1 2]]
[[3 4]]
[[1 2]
 [3 4]]


In [3]:
x_list = []
x1 = np.array([[1, 2], [3, 4]])
print(x1)
x_list.append(x1)
x2 = np.array([[5, 6], [7, 8]])
print(x2)
x_list.append(x2)
x_comb = np.concatenate(x_list, axis=0)
print(x_comb)
print(x_comb[0])
print(x_comb[0][1])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2]
2


In [4]:
x3 = np.array([[9, 10], [11, 12]])
print(x3)
x_comb = np.concatenate([x_comb, x3], axis=0)
print(x_comb)

[[ 9 10]
 [11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [5]:
from rl_vcf.rl.utils import kl_divergence_diag_gaussians

In [10]:
mu1 = np.array([[0, 0], [1, 1]])
std1 = np.array([[1, 1], [1, 1]])
mu2 = np.array([[1, 1], [2, 2]])
std2 = np.array([[1.5, 1.5], [2, 2]])
kl = kl_divergence_diag_gaussians(mu1, std1, mu2, std2)
print(kl)

[0.69981911 0.88629436]
